package model;

import databaseconfig.DBConnection;
import java.sql.*;
import java.util.ArrayList;

/**
 * Manages the collection of competitors stored in the database.
 * <p>
 * This class serves as the central data manager for the application. It handles:
 * </p>
 * <ul>
 * <li><b>Authentication:</b> Registering new users and logging them in.</li>
 * <li><b>Data Retrieval:</b> Loading all competitor data for reports.</li>
 * <li><b>Statistics:</b> Calculating the top performer and score frequencies.</li>
 * </ul>
 *
 * @author Piyush
 * @version 2.0
 */
public class CompetitorList {

    /**
     * A list to hold PiyCompetitor objects loaded from the database.
     * Used primarily for generating reports.
     */
    private ArrayList<PiyCompetitor> competitors;

    /**
     * Constructs a new, empty CompetitorList.
     * <p>
     * Initializes the internal ArrayList to hold competitor data.
     * </p>
     */
    public CompetitorList() {
        this.competitors = new ArrayList<>();
    }

    // =============================================================
    // PART 1: REPORTING METHODS
    // =============================================================

    /**
     * Connects to the database and loads ALL competitors into the internal list.
     * <p>
     * This method clears any existing data in the list before fetching fresh data
     * from the 'Competitors' table. It is essential to call this before running
     * any report generation methods.
     * </p>
     */
    public void loadFromDatabase() {
        competitors.clear(); // Clear old data
        String sql = "SELECT * FROM Competitors";

        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                // Convert database row to Competitor object
                PiyCompetitor c = mapRowToCompetitor(rs);
                competitors.add(c);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Retrieves the list of all loaded competitors.
     *
     * @return An ArrayList containing PiyCompetitor objects representing all users in the database.
     */
    public ArrayList<PiyCompetitor> getAllCompetitors() {
        return competitors;
    }

    /**
     * Identifies the competitor with the highest overall score.
     * <p>
     * Iterates through the loaded list of competitors and compares their overall scores.
     * </p>
     *
     * @return The PiyCompetitor with the highest score, or null if the list is empty.
     */
    public PiyCompetitor getTopPerformer() {
        if (competitors.isEmpty()) return null;

        PiyCompetitor top = competitors.get(0);
        for (PiyCompetitor c : competitors) {
            if (c.getOverallScore() > top.getOverallScore()) {
                top = c;
            }
        }
        return top;
    }

    /**
     * Generates a statistical frequency report of individual scores.
     * <p>
     * Counts how many times each score (0 to 5) appears across all competitors
     * and formats the result into a readable string table.
     * </p>
     *
     * @return A String containing the frequency distribution of scores.
     */
    public String getScoreFrequencyReport() {
        int[] frequency = new int[6]; // Scores 0-5

        for (PiyCompetitor c : competitors) {
            for (int score : c.getScores()) {
                if (score >= 0 && score <= 5) {
                    frequency[score]++;
                }
            }
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Score:     0   1   2   3   4   5\n");
        sb.append("Frequency: ");
        for (int f : frequency) {
            sb.append(String.format("%-4d", f));
        }
        return sb.toString();
    }

    // =============================================================
    // PART 2: AUTHENTICATION METHODS
    // =============================================================

    /**
     * Registers a new competitor in the database.
     * <p>
     * Inserts a new record into the 'Competitors' table with default scores set to 0
     * and the level set to "Beginner".
     * </p>
     *
     * @param firstName The first name of the competitor.
     * @param lastName  The last name of the competitor.
     * @param country   The country the competitor represents.
     * @param password  The password for the user's account.
     * @return The unique competitor ID generated by the database, or -1 if the operation fails.
     */
    public int addCompetitor(String firstName, String lastName, String country, String password) {
        String fullName = firstName + " " + lastName;
        String sql = "INSERT INTO Competitors (name, country, password, level, score1, score2, score3, score4, score5) VALUES (?, ?, ?, 'Beginner', 0,0,0,0,0)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, fullName);
            pstmt.setString(2, country);
            pstmt.setString(3, password);

            int rows = pstmt.executeUpdate();
            if (rows > 0) {
                ResultSet rs = pstmt.getGeneratedKeys();
                if (rs.next()) return rs.getInt(1);
            }
        } catch (SQLException e) { e.printStackTrace(); }
        return -1;
    }

    /**
     * Authenticates a user and retrieves their full details.
     * <p>
     * Checks the database for a matching ID and password. If found, it creates
     * and returns a PiyCompetitor object populated with the user's data and scores.
     * </p>
     *
     * @param competitorId The unique ID of the competitor.
     * @param password     The password provided by the user.
     * @return A PiyCompetitor object if authentication is successful; null otherwise.
     */
    public PiyCompetitor getCompetitor(int competitorId, String password) {
        String sql = "SELECT * FROM Competitors WHERE competitor_id = ? AND password = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, competitorId);
            pstmt.setString(2, password);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) return mapRowToCompetitor(rs);
        } catch (SQLException e) { e.printStackTrace(); }
        return null;
    }

    /**
     * Helper method to convert a database ResultSet row into a PiyCompetitor object.
     *
     * @param rs The ResultSet positioned at the current row.
     * @return A fully populated PiyCompetitor object.
     * @throws SQLException If a database access error occurs.
     */
    private PiyCompetitor mapRowToCompetitor(ResultSet rs) throws SQLException {
        int id = rs.getInt("competitor_id");
        String nameStr = rs.getString("name");
        String level = rs.getString("level");
        String country = rs.getString("country");

        String[] parts = nameStr.split(" ");
        Name nameObj = (parts.length >= 2) ? new Name(parts[0], parts[1]) : new Name(parts[0], "");

        PiyCompetitor user = new PiyCompetitor(id, nameObj, level, country);

        int[] scores = {
                rs.getInt("score1"), rs.getInt("score2"),
                rs.getInt("score3"), rs.getInt("score4"), rs.getInt("score5")
        };
        user.setScores(scores);
        return user;
    }
}